Oscar dev
Luckiifirpo/PF-Huellitas-de-amor pull request #8
Opened 2023-01-17 22:42 UTC by Oskarp88

ruta get de usuarios y animales

2023-01-17 22:48 UTC, wcamest approved these changes

2023-01-17 23:32 UTC, Luckiifirpo requested changes
Veo que hicimos las cosas un poco diferente, te parece si lo acomodamos? porque ambos creamos carpetas controllers, yo cree middlewares, y se nos puede hacer un desastre inmanejable jajajaj, espero tu respuesta!

2023-01-18 02:16 UTC, Alexpalagomez1255 approved these changes

2023-01-18 02:45 UTC, Oskarp88 commented
Veo nosé jeje siempre lo hago con controllers ya que midlewares lo asoció a Morgan, headers el ect, como intermediarios, pero hay que ver cómo hacemos

2023-01-18 02:48 UTC, Luckiifirpo commented
Por eso, mañana podemos hacer una reunión y arreglamos bien como organizamos el back

2023-01-18 13:18 UTC, closed without merging